# Generated by Django 2.2.1 on 2019-05-20 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Artist',
            new_name='artist',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
    ]
