# Generated by Django 2.2.1 on 2019-05-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20190520_0532'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vote',
            field=models.IntegerField(default=0),
        ),
    ]
